language: common-lisp
sudo: false

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre
env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
#    - LISP=ccl-bin
#    - LISP=ecl
#    - LISP=abcl
#    - LISP=allegro
#    - LISP=clisp
#    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=abcl
    - env: LISP=clisp
    - env: LISP=cmucl

os:
#  - osx
  - linux

install:
  - env | sort
  - locale
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install asdf/3.3.3.3
#  - ros install rove
#  - ros install 40ants/cl-info

before_script:
  - ros --version
  - ros config
#  - cl-info

script:
  - echo DONE
#  - rove hamcrest-test.asd
