language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=cmucl
    - env: LISP=ecl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl -- --version
  - cl -e '(princ (lisp-implementation-type))
           (terpri)
           (princ (lisp-implementation-version))
           (terpri)
           (uiop:quit 0)'

  - cl -e '(ql:quickload :prove)
           (ql:quickload :hamcrest-test)
           (if (prove:run-test-system :hamcrest-test)
             (uiop:quit 0)
             (uiop:quit 1))'