version: 2
jobs:
  ccl:
    docker:
      - image: 40ants/base-lisp-image:0.6.0-ccl-bin
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python-pip
            ros install rove
            ros install 40ants/cldomain
            touch qlfile
            qlot install
      - run:
          name: Check environment
          command: env | sort && pwd && echo 'Current dir:' && ls -lh && echo "/app dir:" && ls -lh /app/
      - run:
          name: Run tests
          command: qlot exec rove hamcrest-test.asd
      - run:
          name: Build docs
          command: ./build-docs-on-ci.sh

workflows:
  version: 2
  build:
    jobs:
      - ccl
