version: 2.1

executors:
  ccl-executor:
    docker:
      - image: 40ants/base-lisp-image:0.6.0-ccl-bin
  sbcl-executor:
    docker:
      - image: 40ants/base-lisp-image:0.6.0-sbcl-bin

jobs:
  ccl:
    executor: ccl-executor
    # environment:
    #   LISP: ccl-bin
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ros install rove
            qlot install
      - run:
          name: Check environment
          command: |
            env | grep -v -i token | sort
            echo 'Current dir:'
            pwd
            ls -lh
      - run:
          name: Run tests
          command: qlot exec rove hamcrest-test.asd

  sbcl:
    executor: sbcl-executor
    # environment:
    #   LISP: ccl-bin
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            ros install rove
            qlot install
      - run:
          name: Check environment
          command: |
            env | grep -v -i token | sort
            echo 'Current dir:'
            pwd
            ls -lh
      - run:
          name: Run tests
          command: qlot exec rove hamcrest-test.asd

  build_docs:
    executor: ccl-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python-pip
            pip install -r docs/requirements.txt
            ros install 40ants/cldomain
            qlot install
      - run:
          name: Check environment
          command: |
            env | grep -v -i token | sort
            echo 'Current dir:'
            pwd
            ls -lh
      - run:
          name: Build docs
          command: ./build-docs.ros --push-to gh-pages

workflows:
  version: 2
  build:
    jobs:
      - ccl:
          filters:
            branches:
              ignore: gh-pages

      - sbcl:
          filters:
            branches:
              ignore: gh-pages

      - build_docs:
          filters:
            branches:
              only: master
