version: 2
jobs:
  ccl:
    docker:
      - image: 40ants/base-lisp-image:0.6.0-ccl-bin
    environment:
      LISP: ccl-bin
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y python-pip
            pip install -r docs/requirements.txt
            ros install rove
            ros install 40ants/cldomain
            touch qlfile
            qlot install
      - run:
          name: Check environment
          command: |
            env | grep -v -i token | sort
            echo 'Current dir:'
            pwd
            ls -lh
      - run:
          name: Run tests
          command: qlot exec rove hamcrest-test.asd
      - run:
          name: Build docs
          command: ./build-docs.ros --push-to gh-pages

workflows:
  version: 2
  build:
    jobs:
      - ccl
